# Cloud Build configuration for Subfrost
# Alternative to GitHub Actions - can be triggered by Cloud Build triggers

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: subfrost-app
  _REPOSITORY: docker-images

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_NETWORK=mainnet'
      - '.'
    timeout: '1200s'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA} \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --port 3000 \
          --cpu 1 \
          --memory 512Mi \
          --min-instances 0 \
          --max-instances 10 \
          --concurrency 80 \
          --timeout 60 \
          --set-env-vars "NODE_ENV=production" \
          --set-env-vars "NEXT_PUBLIC_NETWORK=mainnet"

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
