/**
 * useSwapUnwrapMutation - One-click Token to BTC (e.g., DIESEL → BTC) via atomic swap + unwrap
 *
 * ============================================================================
 * ⚠️⚠️⚠️ CRITICAL: BROWSER WALLET OUTPUT ADDRESS BUG (2026-03-01) ⚠️⚠️⚠️
 * ============================================================================
 *
 * When using browser wallets (Xverse, OYL, etc.), you MUST pass ACTUAL addresses
 * to toAddresses/changeAddress/alkanesChangeAddress — NOT symbolic addresses like
 * 'p2tr:0' or 'p2wpkh:0'. Symbolic addresses resolve to SDK's DUMMY wallet!
 *
 * See useSwapMutation.ts header comment for full documentation of this bug,
 * including the transaction that lost user tokens:
 * TX: 985436b5c5c850bd121cd4862f32413f467145b121d34c006417724d71588db9
 *
 * REQUIRED PATTERN:
 * ```typescript
 * const toAddresses = useActualAddresses ? [taprootAddress] : ['p2tr:0'];
 * const changeAddr = useActualAddresses ? segwitAddress : 'p2wpkh:0';
 * const alkanesChangeAddr = useActualAddresses ? taprootAddress : 'p2tr:0';
 * ```
 * ============================================================================
 *
 * ## How It Works
 *
 * This hook combines swap (DIESEL → frBTC) and unwrap (frBTC → BTC) into a single
 * Bitcoin transaction using protostones chained together:
 *
 * 1. **p0 (Auto-edict)**: Generated by SDK from `inputRequirements`
 *    - Transfers sell tokens (DIESEL) to p1 (swap call)
 *
 * 2. **p1 (Swap)**: Calls factory contract with opcode 13 (SwapExactTokensForTokens)
 *    - Input: DIESEL from p0 as `incomingAlkanes`
 *    - Output: frBTC directed to p2 (unwrap call) via pointer=p2
 *
 * 3. **p2 (Unwrap)**: Calls frBTC contract with opcode 78
 *    - Input: frBTC from p1 as `incomingAlkanes`
 *    - Output: BTC to user address (v0)
 *
 * Note: We route through the factory (opcode 13) instead of calling the pool
 * directly because the deployed pool logic is missing the Swap opcode (3).
 *
 * ## Transaction Output Ordering
 *
 * - Output 0 (v0): User taproot address (receives final BTC)
 * - Output 1 (v1): Signer address (for unwrap BTC output)
 * - Output 2+: Change, OP_RETURN
 *
 * ### Journal: 2026-01-28 — Factory router fix applied
 *
 * Previously p1 called the pool directly with opcode 3 (Swap). The deployed pool
 * WASM at [4:65496] is missing opcode 3 — an older build. Swaps silently failed
 * on-chain (no alkane state changes, no revert visible to user).
 *
 * FIX: p1 now calls the factory [4:65498] with opcode 13 (SwapExactTokensForTokens).
 * The factory has working router logic that executes swaps through pools internally.
 * Cellpack format: [factory_block, factory_tx, 13, path_len, ...path, amount_in, min_out, deadline]
 *
 * See useSwapMutation.ts journal entry for full investigation details.
 *
 * @see useWrapSwapMutation.ts - The reverse flow (BTC → Token)
 * @see useSwapMutation.ts - Standalone swap logic
 * @see useUnwrapMutation.ts - Standalone unwrap logic
 */
import { useMutation, useQueryClient } from '@tanstack/react-query';
import BigNumber from 'bignumber.js';
import { useWallet } from '@/context/WalletContext';
import { useTransactionConfirm } from '@/context/TransactionConfirmContext';
import { useSandshrewProvider } from '@/hooks/useSandshrewProvider';
import { getConfig } from '@/utils/getConfig';
import { getTokenSymbol } from '@/lib/alkanes-client';
import { FRBTC_WRAP_FEE_PER_1000 } from '@/constants/alkanes';
import { useFrbtcPremium } from '@/hooks/useFrbtcPremium';
import {
  calculateMinimumFromSlippage,
  getFutureBlockHeight,
} from '@/utils/amm';
import * as bitcoin from 'bitcoinjs-lib';
import * as ecc from '@bitcoinerlab/secp256k1';
// NOTE: Only patching INPUTS (witnessUtxo + redeemScript), NOT outputs
// Output patching was removed - see useSwapMutation.ts for why
import { patchInputsOnly } from '@/lib/psbt-patching';
import { buildSwapUnwrapProtostone } from '@/lib/alkanes/builders';
import { getBitcoinNetwork, getSignerAddress, extractPsbtBase64 } from '@/lib/alkanes/helpers';

bitcoin.initEccLib(ecc);

export type SwapUnwrapTransactionData = {
  sellCurrency: string;     // Token to sell (e.g., "2:0" for DIESEL)
  sellAmount: string;       // Amount in alks
  sellSymbol?: string;      // Symbol for confirmation display (e.g., "DIESEL")
  btcAmount?: string;       // BTC amount for confirmation display
  expectedBtcAmount: string; // Expected BTC output in alks (sats)
  maxSlippage: string;      // Percent string, e.g., '0.5'
  feeRate: number;          // sats/vB
  poolId?: { block: string | number; tx: string | number }; // Pool reference (not used for routing)
  deadlineBlocks?: number;  // Default 3
};

export function useSwapUnwrapMutation() {
  throw new Error('DEPRECATED: useSwapUnwrapMutation does not work. Token→BTC swaps use the two-step flow in SwapShell.tsx (swapMutation → mine → unwrapMutation). See header comment.');

  const { account, network, isConnected, signTaprootPsbt, signSegwitPsbt, walletType } = useWallet();
  const provider = useSandshrewProvider();
  const queryClient = useQueryClient();
  const { requestConfirmation } = useTransactionConfirm();
  const { FRBTC_ALKANE_ID, ALKANE_FACTORY_ID } = getConfig(network);

  // Fetch dynamic frBTC wrap/unwrap fees
  const { data: premiumData } = useFrbtcPremium();
  const unwrapFee = premiumData?.unwrapFeePerThousand ?? FRBTC_WRAP_FEE_PER_1000;

  return useMutation({
    mutationFn: async (data: SwapUnwrapTransactionData) => {

      if (!isConnected) throw new Error('Wallet not connected');
      if (!provider) throw new Error('Provider not available');

      // Get addresses
      // JOURNAL ENTRY (2026-03-01): Support single-address wallets (UniSat, OKX)
      // UniSat/OKX only provide one address type at a time (user-configurable).
      // We need at least ONE address, but don't require both taproot AND segwit.
      const taprootAddress = account?.taproot?.address;
      const segwitAddress = account?.nativeSegwit?.address;
      if (!taprootAddress && !segwitAddress) {
        throw new Error('No wallet address available. Please connect a wallet first.');
      }
      // For alkane operations, prefer taproot if available (alkanes use P2TR)
      const primaryAddress = taprootAddress || segwitAddress;

      const signerAddress = getSignerAddress(network);
      const btcNetwork = getBitcoinNetwork(network);


      // Calculate minimum frBTC from swap (accounting for slippage)
      // The swap outputs frBTC which then gets unwrapped to BTC
      const minFrbtcFromSwap = calculateMinimumFromSlippage({
        amount: data.expectedBtcAmount, // frBTC amount ≈ BTC amount (1:1 minus fees)
        maxSlippage: data.maxSlippage,
      });


      // Get deadline block height (regtest uses large offset so deadline never expires)
      const isRegtest = network === 'regtest' || network === 'subfrost-regtest' || network === 'regtest-local';
      const deadlineBlocks = isRegtest ? 1000 : (data.deadlineBlocks || 3);
      const deadline = await getFutureBlockHeight(deadlineBlocks, provider as any);

      // Build combined protostone
      const protostone = buildSwapUnwrapProtostone({
        sellTokenId: data.sellCurrency,
        sellAmount: new BigNumber(data.sellAmount).integerValue(BigNumber.ROUND_FLOOR).toString(),
        frbtcId: FRBTC_ALKANE_ID,
        factoryId: ALKANE_FACTORY_ID,
        minFrbtcOutput: new BigNumber(minFrbtcFromSwap).integerValue(BigNumber.ROUND_FLOOR).toString(),
        deadline: deadline.toString(),
      });


      // Input requirements: The sell token (DIESEL)
      const [sellBlock, sellTx] = data.sellCurrency.split(':');
      const inputRequirements = `${sellBlock}:${sellTx}:${new BigNumber(data.sellAmount).integerValue(BigNumber.ROUND_FLOOR).toString()}`;

      const isBrowserWallet = walletType === 'browser';
      const useActualAddresses = isBrowserWallet || network === 'devnet';

      // ============================================================================
      // ⚠️ CRITICAL: Browser wallets need ACTUAL addresses, not symbolic ⚠️
      // ============================================================================
      // Symbolic addresses (p2tr:0, p2wpkh:0) resolve to the SDK's DUMMY wallet.
      // Bug fixed: 2026-03-01 - see useSwapMutation.ts for full documentation.
      // ============================================================================
      const fromAddresses = useActualAddresses
        ? [segwitAddress, taprootAddress].filter(Boolean) as string[]
        : ['p2wpkh:0', 'p2tr:0'];

      // JOURNAL ENTRY (2026-03-01): For single-address wallets, use primaryAddress
      // TypeScript can't infer from the early return that primaryAddress is defined, use assertion
      const toAddresses = useActualAddresses
        ? [primaryAddress!, primaryAddress!]
        : ['p2tr:0', 'p2tr:0'];

      const changeAddr = useActualAddresses
        ? (segwitAddress || taprootAddress)
        : 'p2wpkh:0';

      const alkanesChangeAddr = useActualAddresses
        ? primaryAddress
        : 'p2tr:0';



      try {
        // Execute using alkanesExecuteTyped
        const result = await provider.alkanesExecuteTyped({
          inputRequirements,
          protostones: protostone,
          feeRate: data.feeRate,
          autoConfirm: false, // We handle signing
          fromAddresses,
          toAddresses,
          changeAddress: changeAddr,
          alkanesChangeAddress: alkanesChangeAddr,
        });


        // Check if SDK auto-completed
        if (result?.txid || result?.reveal_txid) {
          const txId = result.txid || result.reveal_txid;
          return { success: true, transactionId: txId };
        }

        // Handle readyToSign state
        if (result?.readyToSign) {
          const readyToSign = result.readyToSign;

          // Convert PSBT to base64
          let psbtBase64: string = extractPsbtBase64(readyToSign.psbt);

          // ============================================================================
          // ⚠️ CRITICAL: PSBT PATCHING REMOVED - DO NOT RE-ADD ⚠️
          // ============================================================================
          // Date Removed: 2026-03-01 (same as useSwapMutation.ts fix)
          // See useSwapMutation.ts:444-483 for full documentation.
          //
          // alkanes-rs SDK creates PSBTs with correct real addresses for browser wallets.
          // patchPsbtForBrowserWallet was CORRUPTING these addresses.
          // ============================================================================


          // ============================================================================
          // Input patching for ALL browser wallet types
          // ============================================================================
          // Different wallets have different requirements:
          // - Xverse: P2SH-P2WPKH (starts with '3'/'2'). Needs redeemScript injection.
          // - UniSat/OKX: Single-address P2TR or P2WPKH. Need witnessUtxo.script patching.
          // - OYL/Leather/Phantom: Native P2WPKH (bc1q). Need witnessUtxo.script patching.
          //
          // patchInputsOnly handles ALL these cases. It does NOT touch outputs (the SDK
          // already creates correct output addresses when we pass actual addresses).
          // ============================================================================
          let finalPsbtBase64 = psbtBase64;
          if (isBrowserWallet) {
            const result = patchInputsOnly({
              psbtBase64,
              network: btcNetwork,
              taprootAddress: taprootAddress!,
              segwitAddress,
              paymentPubkeyHex: account?.nativeSegwit?.pubkey,
            });
            finalPsbtBase64 = result.psbtBase64;
            if (result.inputsPatched > 0) {
            }
          }

          // For keystore wallets, request user confirmation before signing
          if (walletType === 'keystore') {
            const approved = await requestConfirmation({
              type: 'swap',
              title: 'Confirm Swap to BTC',
              description: 'Swap to frBTC, then unwrap to BTC',
              fromAmount: (parseFloat(data.sellAmount) / 1e8).toString(),
              fromSymbol: getTokenSymbol(data.sellCurrency, data.sellSymbol),
              fromId: data.sellCurrency,
              toAmount: data.btcAmount,
              toSymbol: 'BTC',
              feeRate: data.feeRate,
            });

            if (!approved) {
              throw new Error('Transaction rejected by user');
            }
          }

          // Sign PSBT — browser wallets sign all input types in a single call,
          // so we must NOT call signPsbt twice (causes "inputType: sh without redeemScript").
          let signedPsbtBase64: string;
          if (isBrowserWallet) {
            signedPsbtBase64 = await signTaprootPsbt(finalPsbtBase64);
          } else {
            signedPsbtBase64 = await signSegwitPsbt(finalPsbtBase64);
            signedPsbtBase64 = await signTaprootPsbt(signedPsbtBase64);
          }

          // Finalize and extract
          const signedPsbt = bitcoin.Psbt.fromBase64(signedPsbtBase64, { network: btcNetwork });
          signedPsbt.finalizeAllInputs();

          const tx = signedPsbt.extractTransaction();
          const txHex = tx.toHex();
          const txid = tx.getId();


          // Log outputs for debugging
          tx.outs.forEach((output, idx) => {
            const script = Buffer.from(output.script).toString('hex');
            if (script.startsWith('6a')) {
            } else {
              try {
                const addr = bitcoin.address.fromOutputScript(output.script, btcNetwork);
                const label = addr === taprootAddress ? 'USER' :
                              addr === signerAddress ? 'SIGNER' : 'OTHER';
              } catch {
              }
            }
          });

          // Broadcast
          const broadcastTxid = await provider.broadcastTransaction(txHex);

          return { success: true, transactionId: broadcastTxid || txid };
        }

        // Handle complete state
        if (result?.complete) {
          const txId = result.complete?.reveal_txid || result.complete?.commit_txid;
          return { success: true, transactionId: txId };
        }

        throw new Error('SwapUnwrap execution did not return a transaction ID');
      } catch (error: any) {
        console.error('═══════════════════════════════════════════════════════════════');
        console.error('[SwapUnwrap] ████ EXECUTE ERROR ████');
        console.error('═══════════════════════════════════════════════════════════════');
        console.error('[SwapUnwrap] Error:', error?.message);
        console.error('[SwapUnwrap] Stack:', error?.stack);
        throw error;
      }
    },
    onSuccess: (data) => {

      // Invalidate all relevant queries
      queryClient.invalidateQueries({ queryKey: ['sellable-currencies'] });
      queryClient.invalidateQueries({ queryKey: ['btc-balance'] });
      queryClient.invalidateQueries({ queryKey: ['frbtc-premium'] });
      queryClient.invalidateQueries({ queryKey: ['dynamic-pools'] });
      queryClient.invalidateQueries({ queryKey: ['poolFee'] });
      queryClient.invalidateQueries({ queryKey: ['alkane-balances'] });
      queryClient.invalidateQueries({ queryKey: ['enriched-wallet'] });
      queryClient.invalidateQueries({ queryKey: ['alkanesTokenPairs'] });
      queryClient.invalidateQueries({ queryKey: ['ammTxHistory'] });

    },
  });
}
